adjective1 = input("Tell me a adjective, and click enter.")
noun1 = input("Tell me a noun, and click enter.")
adjective2 = input("Tell me a adjective, and click enter.")
noun2 = input("Tell me a noun, and click enter.")
verb1 = input("Tell me a verb, and click enter.")
noun3 = input("Tell me a noun, and click enter.")
verb2 = input("Tell me a verb, and click enter.")
noun4 = input("Tell me a noun, and click enter.")
adjective3 = input("Tell me a adjective, and click enter.")
verb3 = input("Tell me a verb, and click enter.")

print("It was another " + adjective1)
print("day, in the city of " + noun1)
print("Well if you can call it a " + adjective2)
print("day. Today is " + noun2)  # A holiday
print("Everyone is " + verb1)
print("around trying to finish their jobs to go " + noun3)
print(".Kids were " + verb2)
print("around the " + noun4)
print(", acting really " + adjective3)
print("all the time but no one is " + verb3)
